
spring:
  application:    name: CMSFORCE
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASS}
  jpa:
     hibernate:
      show-sql: false
       
logging:
  config:
  file: /home/ec2-user/.jenkins/workspace/CMSforce/CMSforce/src/main/resources/ErrorLog.html
  
  
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
   
    
    com.revature: error, info
    org.hibernate: error, warn
    org.apache.catalina: off
    com.zaxxer.hikari: off

       

server:
  port: 9002
eureka:

  client:

    service-url:

      defaultZone: http://localhost:8761/eureka/

  instance:

    lease-expiration-duration-in-seconds: 2

    lease-renewal-interval-in-seconds: 1



  
          
      



